<div class="homepage">
	
	<div id="slider">
		<div class="slidercontrolwr-left">
			<div class="slidercontrol">
				<a href="#" class="aprev" title="Previous" onClick="my_glider.previous();return false;">Previous</a>
			</div>
		</div>
		<div class="slidercontrolwr-right">
			<div class="slidercontrol">
				<a href="#" class="anext" title="Next" onClick="my_glider.next();return false">next</a>
			</div>	
		</div>
	    <div class="scroller">
	    	<div class="content">
					<div class="section" id="section1">
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('strongsauk-home-slider1')->toHtml() ?>
	    		</div>
					<div class="section" id="section2">
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('strongsauk-home-slider2')->toHtml() ?>
	    		</div>
	    		<div class="section" id="section3">
	    			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('strongsauk-home-slider3')->toHtml() ?>
	    		</div>
	    	</div>
	    </div>
	</div>
	<script src="<?php echo $this->getSkinUrl('js/') ?>glider.js" type="text/javascript"></script>
	<script type="text/javascript" charset="utf-8">
		var my_glider = new Glider('slider', {duration:1, autoGlide: true, frequency: 5, initialSection: 'section1'});
	</script>
	
	<div class="home-right">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('strongsauk-home-topbox')->toHtml() ?>
	</div>
	<div class="clearer"></div>
	
	<div class="content">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('strongsauk-home-content')->toHtml() ?>
	</div>

	<div class="clearer"></div>

</div>